// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BDDTest.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Merchant")]
    public partial class MerchantFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "Merchant.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Merchant", "          Merchant Scenarios for Sadad portal ", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 4
#line hidden
#line 5
    testRunner.Given("The user logins successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create Merchant")]
        [NUnit.Framework.CategoryAttribute("CreateMerchant")]
        public void CreateMerchant()
        {
            string[] tagsOfScenario = new string[] {
                    "CreateMerchant"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create Merchant", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 9
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
#line 11
 testRunner.Given("The user is Navigated to the CreateMerchant form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "TermType",
                            "SwitchType",
                            "DivisionCode",
                            "PersonType",
                            "Firstname",
                            "FirstnameEn",
                            "NationalCode",
                            "ParentShaparakMccCode",
                            "ShaparakMcc",
                            "JobTitle",
                            "EmailAddress",
                            "WebSite",
                            "MerchantMobileNo",
                            "OtherOrgAgency",
                            "BirthDate",
                            "LicenseDate",
                            "LastName",
                            "LastNameEN",
                            "FatherName",
                            "IdentityNo",
                            "IdNoSerial",
                            "LetterID",
                            "IdNoSeriesNumber",
                            "MaritalStatus",
                            "SexCode",
                            "PassExpiryDate",
                            "PassportNo"});
                table5.AddRow(new string[] {
                            "درگاه اینترنتی",
                            "سوییچ دو",
                            "تست سداد",
                            "حقیقی",
                            "رامین",
                            "Ramin",
                            "0783431805",
                            "تعاونی مسکن",
                            "تعاونی مسکن",
                            "حسابدار",
                            "accounttest@sadadpsp.ir",
                            "https://www.test22.com",
                            "9125525252",
                            "تست عاملیت",
                            "1368/05/18",
                            "1368/05/10",
                            "فرجی",
                            "Faraji",
                            "سعید",
                            "0082282838",
                            "614351",
                            "ب",
                            "35",
                            "مجرد",
                            "مرد",
                            "1401/02/01",
                            "25251236"});
                table5.AddRow(new string[] {
                            "پایانه فروشگاهی",
                            "سوییچ دو",
                            "تست سداد",
                            "حقیقی",
                            "رامین",
                            "Ramin",
                            "0783431805",
                            "تعاونی مسکن",
                            "تعاونی مسکن",
                            "حسابدار",
                            "accounttest@sadadpsp.ir",
                            "https://www.test22.com",
                            "9125525252",
                            "تست عاملیت",
                            "1368/05/18",
                            "1368/05/10",
                            "فرجی",
                            "Faraji",
                            "سعید",
                            "0082282838",
                            "614351",
                            "ب",
                            "35",
                            "مجرد",
                            "مرد",
                            "1401/02/01",
                            "25251236"});
                table5.AddRow(new string[] {
                            "پایانه فروشگاهی",
                            "سوییچ دو",
                            "تست سداد",
                            "حقوقی",
                            "رامین",
                            "Ramin",
                            "0783431805",
                            "تعاونی مسکن",
                            "تعاونی مسکن",
                            "حسابدار",
                            "accounttest@sadadpsp.ir",
                            "https://www.test22.com",
                            "9125525252",
                            "تست عاملیت",
                            "1368/05/18",
                            "1368/05/10",
                            "فرجی",
                            "Faraji",
                            "سعید",
                            "0082282838",
                            "614351",
                            "ب",
                            "35",
                            "مجرد",
                            "مرد",
                            "1401/02/01",
                            "25251236"});
#line 12
    testRunner.When("The user fills out merchant information as following :", ((string)(null)), table5, "When ");
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "TxtAddressTypeCode",
                            "TxtCityPK",
                            "TelephoneNo",
                            "CitySection",
                            "AddressFull",
                            "AddressFullEN",
                            "Postalcode"});
                table6.AddRow(new string[] {
                            "آدرس محل کار",
                            "تهران",
                            "21-22855252",
                            "3",
                            "خ شریعتی",
                            "Shariati St",
                            "1541697123"});
#line 19
 testRunner.And("The user fills Merchant address information as following:", ((string)(null)), table6, "And ");
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "RowSig",
                            "SigNationality",
                            "SigFirstname",
                            "SigLastname",
                            "SigNationalcode",
                            "SigPassNo",
                            "SigBirthdate"});
                table7.AddRow(new string[] {
                            "2",
                            "ایران",
                            "امید",
                            "حاجی",
                            "0440034922",
                            "13524163",
                            "1362/10/09"});
#line 23
    testRunner.And("The user fill signatory information as following:", ((string)(null)), table7, "And ");
#line hidden
#line 26
 testRunner.And("The user submits", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 27
    testRunner.Then("The Merchant should be created successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Edit Merchant")]
        [NUnit.Framework.CategoryAttribute("EditMerchant")]
        [NUnit.Framework.TestCaseAttribute("000000000000929", null)]
        public void EditMerchant(string cardAcqId, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "EditMerchant"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("CardAcqId", cardAcqId);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Edit Merchant", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 33
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
#line 35
    testRunner.Given("The user navigated to the Merchant Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 36
 testRunner.And(string.Format("The user searches for a merchant based on CardAcqId {0}", cardAcqId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 37
 testRunner.And("The user edits the specfied merchant", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "DivisionCode",
                            "PersonType",
                            "Firstname",
                            "FirstnameEn",
                            "NationalCode",
                            "ParentShaparakMccCode",
                            "ShaparakMcc",
                            "JobTitle",
                            "EmailAddress",
                            "WebSite",
                            "MerchantMobileNo",
                            "OtherOrgAgency",
                            "BirthDate",
                            "LicenseDate",
                            "LastName",
                            "LastNameEN",
                            "FatherName",
                            "IdentityNo",
                            "IdNoSerial",
                            "LetterID",
                            "IdNoSeriesNumber",
                            "MaritalStatus",
                            "SexCode",
                            "PassExpiryDate",
                            "PassportNo"});
                table8.AddRow(new string[] {
                            "تست سداد",
                            "حقیقی",
                            "رامین",
                            "Ramin",
                            "0783431805",
                            "خ",
                            "س",
                            "حسابدار",
                            "accounttest@sadadpsp.ir",
                            "https://www.test22.com",
                            "9125525252",
                            "تست عاملیت",
                            "1368/05/18",
                            "1368/05/10",
                            "فرجی",
                            "Faraji",
                            "سعید",
                            "0082282838",
                            "614351",
                            "الف",
                            "35",
                            "مجرد",
                            "مرد",
                            "1401/02/01",
                            "25251236"});
                table8.AddRow(new string[] {
                            "تست سداد",
                            "حقیقی",
                            "رامین",
                            "Ramin",
                            "0783431805",
                            "تعاونی مسکن",
                            "تعاونی مسکن",
                            "حسابدار",
                            "accounttest@sadadpsp.ir",
                            "https://www.test22.com",
                            "9125525252",
                            "تست عاملیت",
                            "1368/05/18",
                            "1368/05/10",
                            "فرجی",
                            "Faraji",
                            "سعید",
                            "0082282838",
                            "614351",
                            "الف",
                            "35",
                            "مجرد",
                            "مرد",
                            "1401/02/01",
                            "25251236"});
                table8.AddRow(new string[] {
                            "تست سداد",
                            "حقوقی",
                            "رامین",
                            "Ramin",
                            "0783431805",
                            "تعاونی مسکن",
                            "تعاونی مسکن",
                            "حسابدار",
                            "accounttest@sadadpsp.ir",
                            "https://www.test22.com",
                            "9125525252",
                            "تست عاملیت",
                            "1368/05/18",
                            "1368/05/10",
                            "فرجی",
                            "Faraji",
                            "سعید",
                            "0082282838",
                            "614351",
                            "الف",
                            "35",
                            "مجرد",
                            "مرد",
                            "1401/02/01",
                            "25251236"});
#line 38
    testRunner.When("The user edit merchant information as following :", ((string)(null)), table8, "When ");
#line hidden
                TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                            "TxtAddressTypeCode",
                            "TxtCityPK",
                            "TelephoneNo",
                            "CitySection",
                            "AddressFull",
                            "AddressFullEN",
                            "Postalcode"});
                table9.AddRow(new string[] {
                            "آدرس محل کار",
                            "تهران",
                            "21-22855252",
                            "3",
                            "خ شریعتی",
                            "Shariati St",
                            "1541697123"});
#line 45
 testRunner.And("The user edit merchant address information as following:", ((string)(null)), table9, "And ");
#line hidden
                TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                            "RowSig",
                            "SigNationality",
                            "SigFirstname",
                            "SigLastname",
                            "SigNationalcode",
                            "SigPassNo",
                            "SigBirthdate"});
                table10.AddRow(new string[] {
                            "33",
                            "ایران",
                            "امید",
                            "حاجی",
                            "0440034922",
                            "13524163",
                            "1362/10/09"});
#line 51
    testRunner.And("The user edit signatory information as following:", ((string)(null)), table10, "And ");
#line hidden
#line 54
    testRunner.Then("The Merchant should be modified successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Clone Merchant")]
        [NUnit.Framework.CategoryAttribute("CloneMerchant")]
        [NUnit.Framework.TestCaseAttribute("000000130880895", null)]
        public void CloneMerchant(string cardAcqId, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "CloneMerchant"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("CardAcqId", cardAcqId);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Clone Merchant", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 64
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
#line 67
   testRunner.Given("The user navigated to the Merchant Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 68
 testRunner.And(string.Format("The user searches for a merchant based on CardAcqId {0}", cardAcqId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 69
   testRunner.And(string.Format("The user clones the specfied merchant {0}", cardAcqId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                            "TermType",
                            "SwitchType",
                            "DivisionCode",
                            "PersonType",
                            "Firstname",
                            "FirstnameEn",
                            "NationalCode",
                            "ParentShaparakMccCode",
                            "ShaparakMcc",
                            "JobTitle",
                            "EmailAddress",
                            "WebSite",
                            "MerchantMobileNo",
                            "OtherOrgAgency",
                            "BirthDate",
                            "LicenseDate",
                            "LastName",
                            "LastNameEN",
                            "FatherName",
                            "IdentityNo",
                            "IdNoSerial",
                            "LetterID",
                            "IdNoSeriesNumber",
                            "MaritalStatus",
                            "SexCode",
                            "PassExpiryDate",
                            "PassportNo"});
                table11.AddRow(new string[] {
                            "درگاه اینترنتی",
                            "سوییچ دو",
                            "تست سداد",
                            "حقیقی",
                            "رامین",
                            "Ramin",
                            "0783431805",
                            "خ",
                            "س",
                            "حسابدار",
                            "accounttest@sadadpsp.ir",
                            "https://www.test22.com",
                            "9125525252",
                            "تست عاملیت",
                            "1368/05/18",
                            "1368/05/10",
                            "فرجی",
                            "Faraji",
                            "سعید",
                            "0082282838",
                            "614351",
                            "الف",
                            "35",
                            "مجرد",
                            "مرد",
                            "1401/02/01",
                            "25251236"});
                table11.AddRow(new string[] {
                            "پایانه فروشگاهی",
                            "سوییچ دو",
                            "تست سداد",
                            "حقیقی",
                            "رامین",
                            "Ramin",
                            "0783431805",
                            "تعاونی مسکن",
                            "تعاونی مسکن",
                            "حسابدار",
                            "accounttest@sadadpsp.ir",
                            "https://www.test22.com",
                            "9125525252",
                            "تست عاملیت",
                            "1368/05/18",
                            "1368/05/10",
                            "فرجی",
                            "Faraji",
                            "سعید",
                            "0082282838",
                            "614351",
                            "الف",
                            "35",
                            "مجرد",
                            "مرد",
                            "1401/02/01",
                            "25251236"});
                table11.AddRow(new string[] {
                            "پایانه فروشگاهی",
                            "سوییچ دو",
                            "تست سداد",
                            "حقوقی",
                            "رامین",
                            "Ramin",
                            "0783431805",
                            "تعاونی مسکن",
                            "تعاونی مسکن",
                            "حسابدار",
                            "accounttest@sadadpsp.ir",
                            "https://www.test22.com",
                            "9125525252",
                            "تست عاملیت",
                            "1368/05/18",
                            "1368/05/10",
                            "فرجی",
                            "Faraji",
                            "سعید",
                            "0082282838",
                            "614351",
                            "الف",
                            "35",
                            "مجرد",
                            "مرد",
                            "1401/02/01",
                            "25251236"});
#line 71
 testRunner.When("The user edit merchant information as following :", ((string)(null)), table11, "When ");
#line hidden
                TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                            "TxtAddressTypeCode",
                            "TxtCityPK",
                            "TelephoneNo",
                            "CitySection",
                            "AddressFull",
                            "AddressFullEN",
                            "Postalcode"});
                table12.AddRow(new string[] {
                            "آدرس محل کار",
                            "تهران",
                            "21-22855252",
                            "3",
                            "خ شریعتی",
                            "Shariati St",
                            "1541697123"});
#line 78
 testRunner.And("The user customize merchant address information as following:", ((string)(null)), table12, "And ");
#line hidden
#line 84
 testRunner.And("The user submits", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 85
    testRunner.Then("The merchant should be cloned successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create Related Merchant")]
        [NUnit.Framework.CategoryAttribute("CreateRelatedMerchant")]
        public void CreateRelatedMerchant()
        {
            string[] tagsOfScenario = new string[] {
                    "CreateRelatedMerchant"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create Related Merchant", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 95
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
#line 98
 testRunner.Given("The user is Navigated to the CreateMerchant form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                            "TermType",
                            "SwitchType",
                            "DivisionCode",
                            "PersonType",
                            "Firstname",
                            "FirstnameEn",
                            "NationalCode",
                            "ParentShaparakMccCode",
                            "ShaparakMcc",
                            "JobTitle",
                            "EmailAddress",
                            "WebSite",
                            "MerchantMobileNo",
                            "OtherOrgAgency",
                            "BirthDate",
                            "LicenseDate",
                            "LastName",
                            "LastNameEN",
                            "FatherName",
                            "IdentityNo",
                            "IdNoSerial",
                            "LetterID",
                            "IdNoSeriesNumber",
                            "MaritalStatus",
                            "SexCode",
                            "PassExpiryDate",
                            "PassportNo"});
                table13.AddRow(new string[] {
                            "درگاه اینترنتی",
                            "سوییچ دو",
                            "تست سداد",
                            "حقیقی",
                            "رامین",
                            "Ramin",
                            "0783431805",
                            "تع",
                            "ت",
                            "حسابدار",
                            "accounttest@sadadpsp.ir",
                            "https://www.test22.com",
                            "9125525252",
                            "تست عاملیت",
                            "1368/05/18",
                            "1368/05/10",
                            "فرجی",
                            "Faraji",
                            "سعید",
                            "0082282838",
                            "614351",
                            "الف",
                            "35",
                            "مجرد",
                            "مرد",
                            "1401/02/01",
                            "25251236"});
                table13.AddRow(new string[] {
                            "پایانه فروشگاهی",
                            "سوییچ دو",
                            "تست سداد",
                            "حقیقی",
                            "رامین",
                            "Ramin",
                            "0783431805",
                            "تعاونی مسکن",
                            "تعاونی مسکن",
                            "حسابدار",
                            "accounttest@sadadpsp.ir",
                            "https://www.test22.com",
                            "9125525252",
                            "تست عاملیت",
                            "1368/05/18",
                            "1368/05/10",
                            "فرجی",
                            "Faraji",
                            "سعید",
                            "0082282838",
                            "614351",
                            "الف",
                            "35",
                            "مجرد",
                            "مرد",
                            "1401/02/01",
                            "25251236"});
                table13.AddRow(new string[] {
                            "پایانه فروشگاهی",
                            "سوییچ دو",
                            "تست سداد",
                            "حقوقی",
                            "رامین",
                            "Ramin",
                            "0783431805",
                            "تعاونی مسکن",
                            "تعاونی مسکن",
                            "حسابدار",
                            "accounttest@sadadpsp.ir",
                            "https://www.test22.com",
                            "9125525252",
                            "تست عاملیت",
                            "1368/05/18",
                            "1368/05/10",
                            "فرجی",
                            "Faraji",
                            "سعید",
                            "0082282838",
                            "614351",
                            "الف",
                            "35",
                            "مجرد",
                            "مرد",
                            "1401/02/01",
                            "25251236"});
#line 99
 testRunner.When("The User fills out merchant information as following :", ((string)(null)), table13, "When ");
#line hidden
                TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                            "TxtAddressTypeCode",
                            "TxtCityPK",
                            "TelephoneNo",
                            "CitySection",
                            "AddressFull",
                            "AddressFullEN",
                            "Postalcode"});
                table14.AddRow(new string[] {
                            "آدرس محل کار",
                            "تهران",
                            "21-22855252",
                            "3",
                            "خ شریعتی",
                            "Shariati St",
                            "1541697123"});
#line 106
 testRunner.And("The user fills Merchant address information as following:", ((string)(null)), table14, "And ");
#line hidden
                TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                            "RowSig",
                            "SigNationality",
                            "SigFirstname",
                            "SigLastname",
                            "SigNationalcode",
                            "SigPassNo",
                            "SigBirthdate"});
                table15.AddRow(new string[] {
                            "2",
                            "ایران",
                            "امید",
                            "حاجی",
                            "0440034922",
                            "13524163",
                            "1362/10/09"});
#line 110
    testRunner.And("The user fill signatory information as following:", ((string)(null)), table15, "And ");
#line hidden
                TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                            "SubMerchantPk",
                            "CommercialCode",
                            "RelationTypeLookupId"});
                table16.AddRow(new string[] {
                            "000000130880829",
                            "1020304050",
                            "نماینده رسمی"});
#line 114
   testRunner.And("The user fill SubMerchant information as following:", ((string)(null)), table16, "And ");
#line hidden
#line 118
 testRunner.And("The user submits", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 119
    testRunner.Then("The related merchant should be created successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Edit Merchant Address")]
        [NUnit.Framework.CategoryAttribute("EditMerchantAddress")]
        [NUnit.Framework.TestCaseAttribute("000000000000071", null)]
        public void EditMerchantAddress(string cardAcqId, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "EditMerchantAddress"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("CardAcqId", cardAcqId);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Edit Merchant Address", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 126
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
#line 129
   testRunner.Given(string.Format("The user searches for a merchant based on CardAcqId {0}", cardAcqId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                            "TxtAddressTypeCode",
                            "TxtCityPK",
                            "TelephoneNo",
                            "CitySection",
                            "AddressFull",
                            "AddressFullEN",
                            "Postalcode"});
                table17.AddRow(new string[] {
                            "آدرس محل کار",
                            "تهران",
                            "21-22855252",
                            "3",
                            "خ شریعتی",
                            "Shariati St",
                            "10101942864"});
#line 130
   testRunner.When("The user updates merchant address information as following:", ((string)(null)), table17, "When ");
#line hidden
#line 133
   testRunner.Then("The merchant Address should be updated successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Change Merchant PersonType to Legal")]
        [NUnit.Framework.CategoryAttribute("ChangeMerchantPersonTypeToLegal")]
        [NUnit.Framework.TestCaseAttribute("000000000000071", null)]
        public void ChangeMerchantPersonTypeToLegal(string cardAcqId, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ChangeMerchantPersonTypeToLegal"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("CardAcqId", cardAcqId);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Change Merchant PersonType to Legal", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 143
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
#line 145
   testRunner.Given(string.Format("The user searches for a merchant based on CardAcqId {0}", cardAcqId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                            "FirstName",
                            "FirstNameEn",
                            "NationalCode",
                            "TxtCountryCode",
                            "LicenseNo",
                            "LicenseDate"});
                table18.AddRow(new string[] {
                            "رامین",
                            "Ramin",
                            "0783431805",
                            "ایران",
                            "خ شریعتی",
                            "1362/10/09"});
#line 146
   testRunner.When("The user fills out legal merchant information as following:", ((string)(null)), table18, "When ");
#line hidden
#line 149
 testRunner.And("The user submits", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 150
    testRunner.Then("The merchant should be changed to Legal successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Change Merchant PersonType to natural")]
        [NUnit.Framework.CategoryAttribute("ChangeMerchantPersonTypeToNatural")]
        [NUnit.Framework.TestCaseAttribute("000000000002745", "حقوقی", null)]
        public void ChangeMerchantPersonTypeToNatural(string cardAcqId, string personType, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ChangeMerchantPersonTypeToNatural"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("CardAcqId", cardAcqId);
            argumentsOfScenario.Add("PersonType", personType);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Change Merchant PersonType to natural", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 159
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
#line 161
   testRunner.Given(string.Format("The user searches for a Legal merchant based on CardAcqId {0} and PersonType {1}", cardAcqId, personType), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                            "Firstname",
                            "FirstnameEn",
                            "NationalCode",
                            "LastName",
                            "LastNameEN",
                            "FatherName",
                            "TxtCountryCode",
                            "IdentityNo",
                            "IdNoSerial",
                            "LetterID",
                            "IdNoSeriesNumber",
                            "MaritalStatus",
                            "SexCode",
                            "PassExpiryDate",
                            "PassportNo"});
                table19.AddRow(new string[] {
                            "رامین",
                            "Ramin",
                            "0783431805",
                            "حاجی",
                            "Haji",
                            "Hossein",
                            "ایران",
                            "0082282838",
                            "614351",
                            "الف",
                            "35",
                            "مجرد",
                            "مرد",
                            "1401/02/01",
                            "25251236"});
#line 162
   testRunner.When("The user fills out natural merchant information as following:", ((string)(null)), table19, "When ");
#line hidden
#line 167
 testRunner.And("The user submits", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 168
    testRunner.Then("The merchant should be changed to natural successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
